# src/tools.py
import sys
import os
import random
from datetime import datetime

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd
import yfinance as yf
import json   # ← Use json instead of str(dict) + ast.literal_eval
from langchain_core.tools import tool
from src.config import Config
from logger import logger


# ===================================================================
# Tool 1: Fetch Real Indian Stock Data (Clean Dates + JSON)
# ===================================================================
@tool
def fetch_market_data(ticker: str) -> str:
    """Fetches last ~30 days of real Indian stock data. Returns clean JSON string."""
    try:
        ticker = ticker.strip().upper()
        if not ticker.endswith(('.NS', '.BO')):
            ticker = ticker + '.NS'  # Auto-add .NS

        stock = yf.Ticker(ticker)
        hist = stock.history(period="1mo", interval="1d")

        if hist.empty:
            raise ValueError("No data returned")

        clean_dates = hist.index.strftime('%d-%m-%Y').tolist()
        today_row = hist.iloc[-1]
        today_open = round(today_row['Open'], 2)
        today_date = today_row.name.strftime('%d-%m-%Y')

        # CLEAN DATA — NO WRAPPER!
        data = {
            "ticker": ticker,
            "date": clean_dates,
            "price": hist['Close'].round(2).tolist(),
            "today_open": today_open,
            "today_date": today_date,
            "currency": "INR"
        }

        df_tail = hist['Close'].round(2).tail(5).to_frame()
        df_tail.index = df_tail.index.strftime('%d-%m-%Y')
        logger.info(f"Real data fetched → {ticker}")
        logger.info(f"Today's Opening Price: ₹{today_open:,.2f} ({today_date})")
        logger.info("Last 5 trading days:\n" + df_tail.to_string())

        return json.dumps(data, ensure_ascii=False)  # ← CLEAN JSON

    except Exception as e:
        logger.warning(f"yfinance failed → fallback")
        # return _fallback_json(ticker)


# def _fallback_json(ticker: str) -> str:
#     """Returns clean JSON with synthetic data"""
#     dates = pd.date_range(end=pd.Timestamp.today(), periods=30)
#     clean_dates = dates.strftime('%d-%m-%Y').tolist()
#     prices = [round(2500 + random.uniform(-300, 300), 2) for _ in range(30)]
#     data = {
#         "ticker": ticker.upper() + ".NS",
#         "date": clean_dates,
#         "price": prices,
#         "today_open": round(prices[-1], 2),
#         "today_date": clean_dates[-1],
#         "currency": "INR (fallback)"
#     }
#     logger.info("Using synthetic fallback data")
#     return json.dumps(data, ensure_ascii=False)


# ===================================================================
# Tool 2: Professional Analysis Report
# ===================================================================
@tool
def calculate_volatility(price_data_json: str) -> str:
    """Parses clean JSON from fetch_market_data and returns beautiful report."""
    try:
        data = json.loads(price_data_json)  # ← Now it's clean!

        prices = pd.Series(data["price"])
        mean = prices.mean()
        std = prices.std()
        high = prices.max()
        low = prices.min()

        report = f"""# Stock Analysis Report

**Ticker**          : {data['ticker']}  
**Currency**        : Indian Rupees (₹)  
**Period**          : Last ~30 trading days  
**Generated On**    : {datetime.now().strftime('%d-%m-%Y %I:%M %p')}

### Key Metrics
| Metric                  | Value                |
|-------------------------|----------------------|
| Average Closing Price   | ₹{mean:,.2f}        |
| Volatility (Std Dev)    | ±₹{std:,.2f}        |
| Highest Close (30d)     | ₹{high:,.2f}        |
| Lowest Close (30d)      | ₹{low:,.2f}         |
| **Today's Opening**     | **₹{data['today_open']:,.2f}**  
| **As of Date**          | **{data['today_date']}** |

*Data source: Yahoo Finance via yfinance*  
*Report auto-generated by FinQuant Pro Agent*

"""

        logger.info("Analysis completed → report ready")
        return report

    except Exception as e:
        msg = f"Analysis failed: {str(e)}"
        logger.error(msg)
        return msg


# ===================================================================
# Tool 3: Save Report (UTF-8 Safe)
# ===================================================================
@tool
def save_report_to_disk(filename: str, content: str) -> str:
    """Saves UTF-8 encoded report to outputs/ folder."""
    Config.ensure_dirs()
    filepath = os.path.join(Config.OUTPUT_DIR, filename)
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Report saved → {filepath}")
        return f"SUCCESS: Report saved to {filepath}"
    except Exception as e:
        logger.error(f"Save failed: {e}")
        return f"FAILED: {e}"


# Export tools
COMPLEX_TOOLS = [fetch_market_data, calculate_volatility, save_report_to_disk]


# ===================================================================
# Run Test
# ===================================================================
if __name__ == "__main__":
    logger.info("=" * 70)
    logger.info("PROFESSIONAL INDIAN STOCK ANALYSIS TOOL STARTED")
    logger.info("=" * 70)

    ticker = "RELIANCE"        # Try: TCS, HDFCBANK, INFY, ITC, etc.

    raw_json = fetch_market_data.invoke({"ticker": ticker})
    report = calculate_volatility.invoke({"price_data_json": raw_json})

    filename = f"{ticker.upper()}_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
    save_report_to_disk.invoke({"filename": filename, "content": report})

    logger.info("FULL TOOL CHAIN EXECUTED SUCCESSFULLY!")
    logger.info(f"Report location → outputs/{filename}")